"use client";
import { useState, useEffect } from 'react';
import { Camera, Sparkles, ShieldCheck, Zap, Copy, ImagePlus, Clock, X, ChevronRight, Share2, Quote, BookOpen } from 'lucide-react';

export default function Home() {
  const [isScanning, setIsScanning] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [activeTab, setActiveTab] = useState(0);
  const [result, setResult] = useState<any>(null);
  
  const [history, setHistory] = useState<any[]>([]);
  const [isHistoryOpen, setIsHistoryOpen] = useState(false);

  useEffect(() => {
    const savedHistory = localStorage.getItem('subtext_history');
    if (savedHistory) setHistory(JSON.parse(savedHistory));
  }, []);

  const saveToHistory = (newResult: any) => {
    const updatedHistory = [newResult, ...history].slice(0, 5);
    setHistory(updatedHistory);
    localStorage.setItem('subtext_history', JSON.stringify(updatedHistory));
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsScanning(true);
    setResult(null);
    setActiveTab(0);

    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = async () => {
      const base64Image = reader.result;

      try {
        const response = await fetch('/api/decode', {
          method: 'POST',
          body: JSON.stringify({ image: base64Image }),
        });
        
        if (!response.ok) {
          alert("The AI servers are experiencing extremely high demand right now. Please try again in a minute!");
          setIsScanning(false);
          return;
        }

        const data = await response.json();
        setResult(data);
        saveToHistory(data);
      } catch (error) {
        alert("Something went wrong on checking the image. Please try again.");
      } finally {
        setIsScanning(false);
      }
    };
  };

  // --- THE CANVAS IMAGE GENERATOR ---
  const handleShareQuote = async (quote: string) => {
    setIsSharing(true);
    try {
      const canvas = document.createElement('canvas');
      canvas.width = 1080;
      canvas.height = 1920; // Perfect IG Story Size
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error("Could not create canvas");

      // 1. Draw Background Gradient
      const gradient = ctx.createLinearGradient(0, 0, 1080, 1920);
      gradient.addColorStop(0, '#0f1218'); // Dark top
      gradient.addColorStop(1, '#05070a'); // Darker bottom
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, 1080, 1920);

      // 2. Draw Subtle Cyan Glow in the center
      const glow = ctx.createRadialGradient(540, 960, 100, 540, 960, 800);
      glow.addColorStop(0, 'rgba(6, 182, 212, 0.15)');
      glow.addColorStop(1, 'rgba(6, 182, 212, 0)');
      ctx.fillStyle = glow;
      ctx.fillRect(0, 0, 1080, 1920);

      // 3. Word-Wrap the Text (We do this FIRST now to find the height)
      ctx.fillStyle = '#f8fafc';
      ctx.font = 'bold 72px sans-serif';
      ctx.textBaseline = 'middle';
      
      const words = quote.split(' ');
      let lines = [];
      let currentLine = '';
      const maxWidth = 880;

      for (let i = 0; i < words.length; i++) {
        const testLine = currentLine + words[i] + ' ';
        const metrics = ctx.measureText(testLine);
        if (metrics.width > maxWidth && i > 0) {
          lines.push(currentLine);
          currentLine = words[i] + ' ';
        } else {
          currentLine = testLine;
        }
      }
      lines.push(currentLine);

      // Calculate where the text should start
      const lineHeight = 100;
      const totalTextHeight = lines.length * lineHeight;
      let startY = 960 - (totalTextHeight / 2);

      // 4. Giant Quote Mark Decoration (Dynamically placed ABOVE the text)
      ctx.fillStyle = 'rgba(6, 182, 212, 0.2)';
      ctx.font = 'bold 300px Georgia, serif';
      ctx.textAlign = 'center';
      // Uses a smart quote “ and places it 100px above the first line
      ctx.fillText('“', 540, startY - 100); 

      // 5. Draw the Text Lines
      // --- ADD THESE TWO LINES TO RESET CONTEXT ---
      ctx.fillStyle = '#f8fafc'; // Re-set fill style to light grey for readability
      ctx.font = 'bold 72px sans-serif'; // Re-set font to the proper size and family
      // --------------------------------------------
      lines.forEach((line, index) => {
        ctx.fillText(line.trim(), 540, startY + (index * lineHeight));
      });

      // 6. Add Branding at the Bottom
      ctx.fillStyle = '#64748b';
      ctx.font = '36px sans-serif';
      ctx.fillText('Generated by SubtextDecode', 540, 1750);
      
      ctx.fillStyle = '#334155';
      ctx.font = 'bold 24px sans-serif';
      ctx.fillText('SPEAK THE UNSPOKEN', 540, 1800);

      // 7. Convert to Image and Trigger Native Share
      const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, 'image/png'));
      if (!blob) throw new Error("Failed to create image");
      
      const file = new File([blob], 'subtext-decode-quote.png', { type: 'image/png' });

      if (navigator.share && navigator.canShare({ files: [file] })) {
        await navigator.share({
          title: 'SubtextDecode Reminder',
          files: [file]
        });
      } else {
        const link = document.createElement('a');
        link.download = 'subtext-decode-quote.png';
        link.href = canvas.toDataURL('image/png');
        link.click();
      }
    } catch (err) {
      console.error("Error generating image:", err);
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <main className="min-h-screen bg-[#05070a] text-slate-200 flex flex-col items-center p-6 font-sans relative">
      
      {/* PERFECTLY CENTERED HEADER */}
      <div className="w-full max-w-sm flex flex-col items-center mb-10 mt-8 text-center">
        <h1 className="text-4xl font-bold tracking-tighter bg-gradient-to-b from-white to-slate-500 bg-clip-text text-transparent">
          SubtextDecode
        </h1>
        <p className="text-slate-500 text-sm mt-2 uppercase tracking-widest">Speak the Unspoken</p>
      </div>

      <div className="relative w-full max-w-sm aspect-[3/4] bg-[#0f1218] rounded-[2rem] border border-slate-800 shadow-2xl overflow-hidden flex flex-col items-center justify-center p-6">
        
        {isScanning ? (
          <div className="w-full h-full space-y-4 pt-4 animate-pulse">
             <div className="absolute top-0 left-0 w-full h-1 bg-cyan-500 shadow-[0_0_20px_#06b6d4] animate-bounce" />
             <div className="h-16 bg-slate-800/50 rounded-xl w-full" />
             <div className="h-20 bg-slate-800/50 rounded-2xl w-full" />
             <div className="h-32 bg-slate-800/50 rounded-2xl w-full" />
             <div className="space-y-2 pt-4">
                <div className="h-12 bg-slate-800/30 rounded-xl w-full" />
                <div className="h-12 bg-slate-800/30 rounded-xl w-full" />
             </div>
             <p className="text-center text-cyan-500 font-mono text-[10px] mt-4 tracking-widest uppercase flex items-center justify-center gap-2">
               <Sparkles className="w-3 h-3 animate-spin" /> Deep Decoding...
             </p>
          </div>
        ) : result && result.interpretations ? (
          
          /* THE RESULTS DASHBOARD */
          <div className="w-full h-full overflow-y-auto space-y-4 pt-4 custom-scrollbar animate-in fade-in slide-in-from-bottom-4 duration-700">
            
            {/* Confidence Badge */}
            <div className={`p-3 rounded-xl border flex flex-col gap-1 ${
              result.confidence_score >= 80 ? "bg-emerald-900/20 border-emerald-800/50" : 
              result.confidence_score >= 60 ? "bg-amber-900/20 border-amber-800/50" : 
              "bg-red-900/20 border-red-800/50"
            }`}>
              <div className="flex justify-between items-center">
                <span className={`text-[10px] uppercase font-bold tracking-widest ${
                  result.confidence_score >= 80 ? "text-emerald-500" : 
                  result.confidence_score >= 60 ? "text-amber-500" : 
                  "text-red-500"
                }`}>
                  {result.confidence_score >= 80 ? "High Confidence" : 
                   result.confidence_score >= 60 ? "Moderate" : "Ambiguous"}
                </span>
                <span className="text-xs font-mono font-bold text-slate-300">
                  {result.confidence_score}%
                </span>
              </div>
              <p className="text-[11px] text-slate-400 leading-tight">
                {result.reasoning}
              </p>
            </div>

            {/* Scenario Tabs */}
            {result.interpretations.length > 1 && (
              <div className="bg-slate-900/50 p-1 rounded-xl flex gap-1 border border-slate-800">
                {result.interpretations.map((interp: any, index: number) => (
                  <button
                    key={index}
                    onClick={() => setActiveTab(index)}
                    className={`flex-1 py-2 px-2 rounded-lg text-[10px] font-bold tracking-wider uppercase transition-all ${
                      activeTab === index 
                        ? "bg-cyan-500/20 text-cyan-400 border border-cyan-500/30 shadow-sm" 
                        : "text-slate-500 hover:text-slate-300 hover:bg-slate-800/50"
                    }`}
                  >
                    {interp.title}
                  </button>
                ))}
              </div>
            )}

            {/* NEW: ENCOURAGING QUOTE CARD */}
            {result.interpretations[activeTab].encouraging_quote && (
              <div className="bg-gradient-to-br from-cyan-950/40 to-slate-900/80 p-5 rounded-2xl border border-cyan-900/50 relative overflow-hidden text-center flex flex-col items-center gap-3">
                <Quote className="text-cyan-500/50 w-6 h-6 mb-1" />
                <p className="text-slate-200 text-sm font-medium leading-relaxed italic">
                  "{result.interpretations[activeTab].encouraging_quote}"
                </p>
                
                <button 
                  onClick={() => handleShareQuote(result.interpretations[activeTab].encouraging_quote)}
                  disabled={isSharing}
                  className="mt-2 w-full py-2.5 bg-cyan-500/10 hover:bg-cyan-500/20 border border-cyan-500/30 text-cyan-400 rounded-xl text-[10px] font-bold uppercase tracking-widest flex items-center justify-center gap-2 transition-all"
                >
                  {isSharing ? <Sparkles className="w-4 h-4 animate-spin" /> : <Share2 className="w-4 h-4" />}
                  {isSharing ? 'Generating Image...' : 'Share to Story'}
                </button>
              </div>
            )}

            {/* Vibe */}
            <div className="bg-slate-900/50 p-4 rounded-2xl border border-slate-800 relative overflow-hidden">
              <div className="absolute top-0 left-0 w-1 h-full bg-cyan-500"></div>
              <p className="text-[10px] text-cyan-500 uppercase font-bold mb-2 tracking-widest">The Vibe</p>
              <p className="text-slate-200 text-sm leading-relaxed font-medium">"{result.interpretations[activeTab].vibe}"</p>
            </div>

            {/* Meaning */}
            <div className="bg-slate-900/50 p-4 rounded-2xl border border-slate-800 relative overflow-hidden">
               <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500"></div>
              <p className="text-[10px] text-indigo-400 uppercase font-bold mb-2 tracking-widest">Hidden Meaning</p>
              <p className="text-slate-300 text-sm leading-relaxed">{result.interpretations[activeTab].hidden_meaning}</p>
            </div>

            {/* Red Flags */}
            {result.interpretations[activeTab].red_flags && result.interpretations[activeTab].red_flags.length > 0 && (
              <div className="bg-rose-950/30 p-4 rounded-2xl border border-rose-900/50 relative overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-rose-500"></div>
                <p className="text-[10px] text-rose-500 uppercase font-bold mb-3 tracking-widest flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-rose-500 animate-pulse"></span>
                  Red Flags Detected
                </p>
                <ul className="space-y-2">
                  {result.interpretations[activeTab].red_flags.map((flag: string, i: number) => (
                    <li key={i} className="text-rose-200/80 text-xs flex items-start gap-2">
                      <span className="text-rose-500 mt-0.5">›</span>
                      {flag}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Response Options */}
            <div className="pt-4 border-t border-slate-800">
              <p className="text-[10px] text-slate-500 uppercase font-bold mb-4 tracking-widest text-center">Suggested Replies</p>
              
              <div className="space-y-3">
                {/* Shield */}
                <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 text-sm relative group transition-colors hover:border-emerald-900/50">
                  <span className="text-[9px] uppercase tracking-wider text-emerald-500 block mb-1 font-bold">The Shield (Boundaries)</span>
                  <p className="pr-8 text-slate-300 text-xs">{result.interpretations[activeTab].replies.shield}</p>
                  <button onClick={() => navigator.clipboard.writeText(result.interpretations[activeTab].replies.shield)} className="absolute top-3 right-3 text-slate-600 hover:text-emerald-400">
                    <Copy size={14} />
                  </button>
                </div>
                {/* Bridge */}
                <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 text-sm relative group transition-colors hover:border-amber-900/50">
                  <span className="text-[9px] uppercase tracking-wider text-amber-500 block mb-1 font-bold">The Bridge (Empathy)</span>
                  <p className="pr-8 text-slate-300 text-xs">{result.interpretations[activeTab].replies.bridge}</p>
                  <button onClick={() => navigator.clipboard.writeText(result.interpretations[activeTab].replies.bridge)} className="absolute top-3 right-3 text-slate-600 hover:text-amber-400">
                    <Copy size={14} />
                  </button>
                </div>
                {/* Suit */}
                <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 text-sm relative group transition-colors hover:border-blue-900/50">
                  <span className="text-[9px] uppercase tracking-wider text-blue-500 block mb-1 font-bold">The Suit (Professional)</span>
                  <p className="pr-8 text-slate-300 text-xs">{result.interpretations[activeTab].replies.suit}</p>
                  <button onClick={() => navigator.clipboard.writeText(result.interpretations[activeTab].replies.suit)} className="absolute top-3 right-3 text-slate-600 hover:text-blue-400">
                    <Copy size={14} />
                  </button>
                </div>
              </div>
            </div>

            <button 
              onClick={() => setResult(null)}
              className="w-full py-3 mt-4 bg-slate-800 rounded-xl text-xs font-bold uppercase tracking-widest hover:bg-slate-700 transition-colors"
            >
              Scan Another
            </button>

          </div>
        ) : (
          
          /* UPLOAD BUTTONS */
          <div className="flex flex-col items-center w-full">
            <div className="flex justify-center gap-8 mb-4">
              <label className="cursor-pointer group flex flex-col items-center gap-3">
                <input type="file" accept="image/*" capture="environment" className="hidden" onChange={handleFileChange} />
                <div className="w-16 h-16 rounded-full bg-slate-800/50 border border-slate-700 flex items-center justify-center group-hover:border-cyan-500/50 group-hover:bg-cyan-500/10 transition-all shadow-lg">
                  <Camera className="w-7 h-7 text-slate-500 group-hover:text-cyan-400" />
                </div>
                <span className="block text-slate-200 font-bold tracking-wide text-sm">Camera</span>
              </label>
              <label className="cursor-pointer group flex flex-col items-center gap-3">
                <input type="file" accept="image/*" className="hidden" onChange={handleFileChange} />
                <div className="w-16 h-16 rounded-full bg-slate-800/50 border border-slate-700 flex items-center justify-center group-hover:border-cyan-500/50 group-hover:bg-cyan-500/10 transition-all shadow-lg">
                  <ImagePlus className="w-7 h-7 text-slate-500 group-hover:text-cyan-400" />
                </div>
                <span className="block text-slate-200 font-bold tracking-wide text-sm">Gallery</span>
              </label>
            </div>
            <span className="text-slate-500 text-[10px] uppercase font-semibold">JPG, PNG, or HEIC</span>
          </div>
        )}
      </div>

      {/* NEW SYMMETRICAL HISTORY BUTTON */}
      <button 
        onClick={() => setIsHistoryOpen(true)}
        className="w-full max-w-sm mt-6 flex items-center justify-center gap-2 p-4 rounded-2xl bg-slate-900/40 border border-slate-800 text-slate-400 hover:text-cyan-400 hover:border-cyan-900/50 transition-all shadow-sm group"
      >
        <Clock size={16} className="group-hover:animate-pulse" />
        <span className="text-xs font-bold uppercase tracking-widest">View Recent Scans</span>
      </button>

      {/* HISTORY DRAWER */}
      {isHistoryOpen && (
        <div className="fixed inset-0 z-50 flex justify-end">
          <div className="absolute inset-0 bg-black/80 backdrop-blur-sm transition-opacity" onClick={() => setIsHistoryOpen(false)} />
          <div className="relative w-80 h-full bg-[#0a0c10] border-l border-slate-800 shadow-2xl p-6 flex flex-col animate-in slide-in-from-right duration-300">
            <div className="flex justify-between items-center mb-8">
              <h2 className="text-lg font-bold tracking-tighter text-slate-200">Recent Scans</h2>
              <button onClick={() => setIsHistoryOpen(false)} className="text-slate-500 hover:text-white transition-colors">
                <X size={20} />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto space-y-3 custom-scrollbar">
              {history.length === 0 ? (
                <p className="text-slate-600 text-xs text-center mt-10 uppercase tracking-widest">No history yet</p>
              ) : (
                history.map((item, i) => (
                  <button 
                    key={i} 
                    onClick={() => { setResult(item); setIsHistoryOpen(false); }}
                    className="w-full text-left p-4 bg-slate-900/50 border border-slate-800 rounded-2xl hover:border-cyan-500/50 transition-all group"
                  >
                    <div className="flex justify-between items-start mb-2">
                      <span className={`text-[9px] font-bold uppercase tracking-widest ${
                        item.confidence_score >= 80 ? "text-emerald-500" : 
                        item.confidence_score >= 60 ? "text-amber-500" : "text-red-500"
                      }`}>
                        {item.confidence_score}% Match
                      </span>
                      <ChevronRight size={14} className="text-slate-600 group-hover:text-cyan-400" />
                    </div>
                    <p className="text-slate-200 text-xs font-medium truncate italic">
                      "{item.interpretations?.[0]?.vibe || "Scan Result"}"
                    </p>
                  </button>
                ))
              )}
            </div>
          </div>
        </div>
      )}

      {/* BOTTOM SECTION */}
      <div className="w-full max-w-sm mt-8 space-y-4 pb-8">
        
        {/* The "About & Tech" Box */}
        <div className="bg-slate-900/40 p-4 rounded-2xl border border-slate-800 shadow-sm flex flex-col gap-4 transition-colors hover:border-slate-700/80">
          <div className="flex justify-center gap-8 pb-3 border-b border-slate-800/60">
            <div className="flex items-center gap-1.5">
              <ShieldCheck className="w-4 h-4 text-emerald-500" />
              <span className="text-[10px] uppercase font-bold tracking-widest text-slate-300">Encrypted</span>
            </div>
            <div className="flex items-center gap-1.5">
              <Zap className="w-4 h-4 text-amber-500" />
              <span className="text-[10px] uppercase font-bold tracking-widest text-slate-300">AI Powered</span>
            </div>
          </div>
          <div className="px-1">
            <h3 className="text-center font-bold text-slate-200 text-xs tracking-wider mb-2 uppercase">Speak the Unspoken</h3>
            <p className="text-[11px] text-slate-400 text-center leading-relaxed">
              Navigate the unspoken. SubtextDecode translates hidden tones and meanings in your digital chats, acting as a social translator for your most tricky conversations.
            </p>
          </div>
        </div>

        {/* Quick Guide */}
        <div className="bg-slate-900/30 p-4 rounded-2xl border border-slate-800/50 transition-colors hover:border-cyan-900/50">
          <p className="text-[10px] text-cyan-500 uppercase font-bold mb-4 tracking-widest text-center">Quick Guide</p>
          <div className="flex justify-between items-start px-2">
            <div className="flex flex-col items-center text-center gap-2 w-1/3">
              <div className="w-7 h-7 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center text-slate-300 text-xs font-bold shadow-lg">1</div>
              <p className="text-[10px] text-slate-400 uppercase font-semibold leading-tight">Snap or<br/>Upload</p>
            </div>
            <div className="w-8 h-[1px] bg-slate-800 mt-3 hidden sm:block"></div>
            <div className="flex flex-col items-center text-center gap-2 w-1/3">
              <div className="w-7 h-7 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center text-slate-300 text-xs font-bold shadow-lg">2</div>
              <p className="text-[10px] text-slate-400 uppercase font-semibold leading-tight">AI Decodes<br/>Subtext</p>
            </div>
            <div className="w-8 h-[1px] bg-slate-800 mt-3 hidden sm:block"></div>
            <div className="flex flex-col items-center text-center gap-2 w-1/3">
              <div className="w-7 h-7 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center text-slate-300 text-xs font-bold shadow-lg">3</div>
              <p className="text-[10px] text-slate-400 uppercase font-semibold leading-tight">Pick Your<br/>Reply</p>
            </div>
          </div>
        </div>

        {/* Scientific Foundations */}
        <div className="bg-slate-900/30 p-4 rounded-2xl border border-slate-800/50 transition-colors hover:border-indigo-900/50">
          <div className="flex items-center justify-center gap-2 mb-4">
            <BookOpen className="w-4 h-4 text-indigo-400" />
            <p className="text-[10px] text-indigo-400 uppercase font-bold tracking-widest text-center">Scientific Foundations</p>
          </div>
          
          <div className="space-y-3">
            {/* Research 1 */}
            <div className="border-l-2 border-indigo-500/30 pl-3">
              <p className="text-[10px] text-slate-300 font-bold uppercase tracking-wider mb-0.5">Double Empathy Problem</p>
              <p className="text-[9px] text-slate-500 leading-relaxed">
                Framing communication gaps as a two-way disjuncture, not a single-sided deficit. <span className="italic">(Milton, 2012)</span>
              </p>
            </div>
            
            {/* Research 2 */}
            <div className="border-l-2 border-indigo-500/30 pl-3">
              <p className="text-[10px] text-slate-300 font-bold uppercase tracking-wider mb-0.5">Negative Interpretation Bias</p>
              <p className="text-[9px] text-slate-500 leading-relaxed">
                Mitigating the cognitive bias in social anxiety that defaults to interpreting ambiguity as hostile. <span className="italic">(Amir et al., 2009)</span>
              </p>
            </div>

            {/* Research 3 */}
            <div className="border-l-2 border-indigo-500/30 pl-3">
              <p className="text-[10px] text-slate-300 font-bold uppercase tracking-wider mb-0.5">AI as a Social Prosthetic</p>
              <p className="text-[9px] text-slate-500 leading-relaxed">
                Utilizing generative models for real-time affective tracking and neurodivergent equity. 
              </p>
            </div>
          </div>
        </div>

      </div>
      
      {/* Creator Credit & Legal Disclaimer */}
      <div className="mt-2 pb-8 text-center w-full max-w-sm px-4">
        <p className="text-[10px] text-slate-600 font-mono tracking-widest uppercase mb-4">
          Engineered by Hafiz Wahid
        </p>
        <p className="text-[8px] text-slate-700 leading-tight">
          Disclaimer: SubtextDecode is an AI-powered experimental tool designed for educational and communicative support. It is not a substitute for professional mental health advice, therapy, or medical diagnosis.
        </p>
      </div>
    </main>
  );
}